FROM debian:buster
RUN apt-get update && \
    apt-get install php-net-socket -y &&\
    apt-get install php-fpm -y &&\
    apt-get install wget -y 


EXPOSE 7000
WORKDIR /var/www/html

RUN sed -i '/listen =/c listen = 7000' /etc/php/7.3/fpm/pool.d/www.conf

run mkdir /var/www/html/adminer && wget "http://www.adminer.org/latest.php" -O /var/www/html/adminer/adminer.php

 COPY ./tools/adminer.sh /adminer.sh
 RUN chmod +x /adminer.sh

ENTRYPOINT  sh /adminer.sh && sleep 2000
