FROM debian:buster
RUN apt-get update && \
    apt-get upgrade && \
    apt-get install nginx -y &&\
    apt-get install php-fpm -y &&\
    apt-get install openssl -y &&\
    ls /etc/nginx 
COPY ./conf/default.conf /etc/nginx/sites-available/default

COPY ./tools/ng.sh /ng.sh
 RUN chmod +x /ng.sh
EXPOSE 8000

run sh /ng.sh 
EXPOSE 443

ENTRYPOINT ["nginx", "-g", "daemon off;"]